language: cpp

compiler:
 - clang

env:
  matrix:
    - CXX11=true TARGET=build_mapnik QUIET=true MAPNIK_BRANCH=master
    - CXX11=true TARGET=build_mapnik QUIET=true MAPNIK_BRANCH=image_data_any BUILD_POSTFIX=raster-ng
  global:
    - secure: Tdy4kT5Zz59e1POud0zwieJ+2ajPaC+5da4cQhS3w+aLs3a8RTd5czfTn8XQPkpViHFX0tr0JIk7vOhCoDmIJkLpr44J3xUwf+gEaJUDCuFPUpd+ddk7tRogMA6Trv12W5D3ZV603uzNdEr7WUv5VfMQo56eK1BI8Z5rGHRNDWo=
    - secure: O4TCbGsvDnHVWn6DwWADdsldR2Re5DQ7JbJvTEqDv3GoOlHhwJRbOJsNAioQ77MgtyP3F4g3xpWGnFT2jHjnoP+NI54impFOstPXVvO4WvZBtx3U8+kiCQOXAn5QQRo4+KDz3fqZiI9PTXUfOF/Bgu2dqcGupGyFDoHEIQudu+0=

before_install:
 - if [[ `uname -s` == 'Darwin' ]]; then vm_stat && sysctl -n hw.memsize; else free; fi
 - if [[ `uname -s` == 'Linux' ]]; then sudo apt-get update; fi

install:
 - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')

before_script:
 - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then echo "publishing" && export PUBLISH=true; else echo "not publishing"; fi;

script:
 - source ./build.sh
 - ${TARGET}
