language: cpp

compiler:
 - gcc
 - clang

env:
  matrix:
    # Cant' copy from non-directory: / atomic_fetch_add_4 undefined
    #- CXX11=true TARGET=mobile_tools PLATFORM=Android
    #- CXX11=false TARGET=mobile_tools PLATFORM=Android
    #- CXX11=true TARGET=build_osmium
    - CXX11=true TARGET=build_osrm QUIET=true LTO=True
    - CXX11=true TARGET=build_osrm QUIET=true
    #- CXX11=true  TARGET=build_mapnik QUIET=true PUBLISH=true MINIMAL_MAPNIK=false LTO=false
    #- CXX11=false TARGET=build_mapnik QUIET=true PUBLISH=true MINIMAL_MAPNIK=false LTO=false
    # broken protobuf-c build
    #- CXX11=false TARGET=build_osm2pgsql QUIET=true
    # broken spatialite configure
    #- CXX11=false TARGET=build_liblas QUIET=true
  global:
    - secure: Tdy4kT5Zz59e1POud0zwieJ+2ajPaC+5da4cQhS3w+aLs3a8RTd5czfTn8XQPkpViHFX0tr0JIk7vOhCoDmIJkLpr44J3xUwf+gEaJUDCuFPUpd+ddk7tRogMA6Trv12W5D3ZV603uzNdEr7WUv5VfMQo56eK1BI8Z5rGHRNDWo=
    - secure: O4TCbGsvDnHVWn6DwWADdsldR2Re5DQ7JbJvTEqDv3GoOlHhwJRbOJsNAioQ77MgtyP3F4g3xpWGnFT2jHjnoP+NI54impFOstPXVvO4WvZBtx3U8+kiCQOXAn5QQRo4+KDz3fqZiI9PTXUfOF/Bgu2dqcGupGyFDoHEIQudu+0=

before_install:
 - if [[ `uname -s` == 'Darwin' ]]; then vm_stat && sysctl -n hw.memsize; else free; fi

install:
 - true

before_script:
 - true

script:
 - source ./build.sh
 - ${TARGET}